import { Box, Container } from "@mui/material"
import { GetServerSideProps } from "next"
import Head from "next/head"
import * as React from "react"
import { getUser } from "../api/users/[userId]"
import { User } from "@/types/userType"
import ProfileCard from "@/components/ProfileCard"

interface UserPageProps {
	user: User
}

export const getServerSideProps: GetServerSideProps = async ( context ) => {
	const userId = context.query.userId

	const user = await getUser( userId as string )

	if( !user ) {
		return {
			props: {}
		}
	}

	return { 
		props: {
			user
		}
	}
}

export default function UserPage( props: UserPageProps ) {
	return (
		<Container
			sx={{
				pt: 3
			}}
		>
			<Head>
				<title>KSUConnect | Log In or Sign up</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Box
					display="flex"
					flexDirection="column"
					alignItems="center"
				>
					<ProfileCard 
						user={props.user}
					/>
				</Box>
			</main>
		</Container>
	)
}
