import PostCard from "@/components/PostCard"
import { Container, Grid, Typography } from "@mui/material"
import Head from "next/head"

export default function Home() {
	return (
		<Container>
			<Head>
				<title>KSUConnect | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Typography variant="h6">Home</Typography>
				<Grid container>
					<Grid item xs={2} sx={{ border: "1px solid red" }}>

					</Grid>
					<Grid item xs={6}>
						<PostCard />
					</Grid>
					<Grid item xs={4} sx={{ border: "1px solid red" }}>

					</Grid>
				</Grid>
			</main>
		</Container>
	)
}
