import { Container, Typography } from "@mui/material"
import Head from "next/head"

export default function Network() {
	return (
		<Container>
			<Head>
				<title>KSUConnect | Network</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Typography variant="h6">Network</Typography>
			</main>
		</Container>
	)
}
