import UserRow from "@/components/UserRow"
import useUser from "@/lib/useUser"
import { User } from "@/types/userType"
import { Box, Button, CircularProgress, Container, Divider, FormControl, InputLabel, MenuItem, Pagination, Select, Stack, Tab, Tabs, Typography } from "@mui/material"
import axios from "axios"
import Head from "next/head"
import * as React from "react"

export default function Network() {
	const [ tabIndex, setTabIndex ] = React.useState( 0 )

	return (
		<Container
			sx={{
				pt: 3
			}}
		>
			<Head>
				<title>KSUConnect | Network</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Box
					sx={{
						backgroundColor: "white",
						borderRadius: 3,
						padding: 2,
					}}
					border="1px solid"
					borderColor="divider"
				>
					<Typography variant="h6">My Network</Typography>
					<Box borderBottom={1} borderColor="divider">
						<Tabs value={tabIndex} onChange={( _, val ) => setTabIndex( val )}>
							<Tab label="Following" />
							<Tab label="Followers" />
							<Tab label="Discover" />
						</Tabs>
					</Box>
					<TabPanel value={tabIndex} index={0}>
						<UsersPanel following />
					</TabPanel>
					<TabPanel value={tabIndex} index={1}>
						<UsersPanel />
					</TabPanel>
					<TabPanel value={tabIndex} index={2}>
						<DiscoverPanel />
					</TabPanel>
				</Box>
			</main>
		</Container>
	)
}

interface TabPanelProps {
	children?: React.ReactNode
	index: number
	value: number
}

function TabPanel( props: TabPanelProps ) {
	return (
		<div
			role="tabpanel"
			hidden={props.value !== props.index}
		>
			{props.value === props.index && (
				<Box p={1} pb={0}>
					{props.children}
				</Box>
			)}
		</div>
	)
}

interface UsersPanelProps {
	following?: boolean
}

function UsersPanel( props: UsersPanelProps ) {
	const { user } = useUser()

	const [ users, setUsers ] = React.useState<User[]>( [] )
	const [ loading, setLoading ] = React.useState( true )

	React.useEffect( () => {
		const fetchUsers = async () => {
			const response = await axios( `/api/${props.following ? "following" : "followers"}/${user?.userId || 0}` )

			const newUsers: User[] = response.data.users

			setUsers( newUsers )
		}

		fetchUsers().then( () => {
			setLoading( false )
		} )
	}, [user?.userId, props.following] )

	return (
		<Stack gap={1}>
			{loading && (
				<CircularProgress 
					sx={{
						alignSelf: "center",
					}}
				/>
			)}
			{!loading && users.length === 0 && (
				<Typography>No users</Typography>
			)}
			{!loading && users.map( user => (
				<UserRow 
					user={user}
					key={user.userId}
				/>
			) )}
		</Stack>
	)
}

function DiscoverPanel() {
	const [status, setStatus] = React.useState( "" )
	const [major, setMajor] = React.useState( "" )
	const [category, setCategory] = React.useState( "" )
	const [statuses, setStatuses] = React.useState<string[]>( [] )
	const [majors, setMajors] = React.useState<string[]>( [] )
	const [categories, setCategories] = React.useState<string[]>( [] )
	const [users, setUsers] = React.useState<User[]>( [] )
	const [loading, setLoading] = React.useState( true )
	const [page, setPage] = React.useState( 1 )
	const [pageCount, setPageCount] = React.useState( 0 )

	const handleClearFilters = React.useCallback( () => {
		setStatus( "" )
		setMajor( "" )
		setCategory( "" )
	}, [] )

	React.useEffect( () => {
		const fetchFilters = async () => {
			const response = await axios( "/api/filters" )

			setStatuses( response.data.statuses )
			setMajors( response.data.majors )
			setCategories( response.data.categories )
		}

		fetchFilters()
	}, [] )

	React.useEffect( () => {
		const fetchUsers = async () => {
			const response = await axios.post( "/api/filters", {
				status,
				major,
				category,
				page
			} )

			setUsers( response.data.users )
			setPageCount( response.data.pageCount )
		}

		setLoading( true )
		setTimeout( () => {
			fetchUsers().then( () => setLoading( false ) )
		}, 1000 )
	}, [status, major, category, page] )

	React.useEffect( () => {
		setPage( 1 )
	}, [status, major, category] )

	return (
		<Stack gap={1}>
			<Stack
				sx={{
					flexDirection: "row",
					alignItems: "center"
				}}
				gap={1}
			>
				<FormControl sx={{ minWidth: 200 }}>
					<InputLabel id="school-status-select">School Status</InputLabel>
					<Select 
						labelId="school-status-select"
						label="School Status"
						value={status}
						onChange={e => setStatus( e.target.value )}
					>
						{statuses.map( item => (
							<MenuItem value={item} key={item}>{item}</MenuItem>
						) )}
					</Select>
				</FormControl>
				<FormControl sx={{ minWidth: 200 }}>
					<InputLabel id="major-select">Major</InputLabel>
					<Select 
						labelId="major-select"
						label="Major"
						value={major}
						onChange={e => setMajor( e.target.value )}
					>
						{majors.map( item => (
							<MenuItem value={item} key={item}>{item}</MenuItem>
						) )}
					</Select>
				</FormControl>
				<FormControl sx={{ minWidth: 200 }}>
					<InputLabel id="category-select">Category</InputLabel>
					<Select 
						labelId="category-select"
						label="Category"
						value={category}
						onChange={e => setCategory( e.target.value )}
					>
						{categories.map( item => (
							<MenuItem value={item} key={item}>{item}</MenuItem>
						) )}
					</Select>
				</FormControl>
				<Button variant="contained" onClick={handleClearFilters}>Clear Filters</Button>
			</Stack>
			<Divider />
			<Pagination sx={{ alignSelf: "center" }} count={pageCount} page={page} onChange={( e, value ) => setPage( value )} />
			<Stack gap={1}>
				{loading && (
					<CircularProgress 
						sx={{
							alignSelf: "center",
						}}
					/>
				)}
				{!loading && users.length === 0 && (
					<Typography>No users</Typography>
				)}
				{!loading && users.map( user => (
					<UserRow 
						user={user}
						key={user.userId}
					/>
				) )}
			</Stack>
		</Stack>
	)
}
